circle.yml
=> [chore] Removing chromedriver & selenium preload

bower.json, gulpfile.js, index.html, js/app.js, js/config/dev.js, js/config/test.js, js/controllers/ctr-add-presentation-modal.js, js/controllers/ctr-add-url-modal.js, js/controllers/ctr-schedule-details.js, js/directives/dtv-schedule-fields.js, js/services/svc-schedule.js, partials/add-presentation-modal.html, partials/add-url-modal.html, partials/schedule-fields.html, test/unit/controllers/ctr-add-url-modal.tests.js
Added selector for URL or Presentation
URL selector contains storage modal instance
Presentation item selector model, no presentation selection implemented
=> [feature] Added UX for playlist item add

index.html, js/app.js, js/controllers/ctr-add-url-modal.js, js/controllers/ctr-schedule-add.js, js/controllers/ctr-schedule-details.js, js/services/svc-schedule-factory.js, partials/schedule-add.html, partials/schedule-details.html, test/unit/controllers/ctr-schedule-add.tests.js, test/unit/controllers/ctr-schedule-details.tests.js, test/unit/services/svc-schedule-factory.tests.js, test/unit/services/svc-schedule.tests.js
Created factory for handling schedule info
Moved controller logic to factory
Load factory on route change
=> [feature] Factory for handling schedule [stage-2]

gulpfile.js, index.html, js/controllers/ctr-add-presentation-modal.js, js/controllers/ctr-presentation-list.js, js/filters/ftr-presentation-status.js, js/services/svc-presentation.js, partials/add-presentation-modal.html, partials/presentation-list.html, partials/schedule-fields.html, test/e2e/add-presentation.scenarios.js, test/e2e/pages/presentationModalPage.js, test/e2e/pages/scheduleAddPage.js, test/unit/controllers/ctr-add-presentation-modal.tests.js, test/unit/controllers/ctr-presentation-list.tests.js, test/unit/filters/ftr-presentation-status.tests.js
[stage-0]
@alex-deaconu please review. I had to disable a e2e test for checking if the presentations are loaded. It is working fine on my local but not on cci. I will troubleshoot it tomorrow. cheers
=> Implemented load of presentation list.

partials/presentation-list.html
and added class text-danger to revised label
[stage-0]
=> Removed the table-selector class

js/controllers/ctr-edit-url-modal.js, test/unit/controllers/ctr-edit-url-modal.tests.js
Needed for the storageSelector
=> [fix] Added missing companyId [stage-1]

bower.json, index.html, js/controllers/ctr-edit-presentation-modal.js, js/controllers/ctr-edit-url-modal.js, js/directives/dtv-playlist-item.js, js/filters/ftr-presentation-status.js, js/services/svc-playlist-factory.js, js/services/svc-presentation.js, js/services/svc-schedule-factory.js, partials/playlist-item.html, partials/playlist.html, test/unit/controllers/ctr-edit-presentation-modal.tests.js, test/unit/controllers/ctr-edit-url-modal.tests.js, test/unit/services/svc-playlist-factory.tests.js, test/unit/services/svc-schedule-factory.tests.js
Empty playlist state
Created separate playlistFactory for playlist functionality
Updated common-style branch
=> [feature] Playlist Item delete and move functionality [stage-2]

circle.yml
=> Use stage-0 if stage tag is missing

partials/playlist.html, partials/schedules-list.html
@alex-deaconu changes for responsiveness / cleanup
=> Responsive Fix

js/controllers/ctr-playlist-item-modal.js, js/directives/dtv-playlist.js, js/directives/dtv-schedule-fields.js, js/services/svc-playlist-factory.js, test/unit/services/svc-playlist-factory.tests.js
=> Fix issue where schedule.content is undefined in the API

js/controllers/ctr-playlist-item-modal.js, js/controllers/ctr-presentation-list.js, partials/presentation-list.html, partials/schedules-list.html, test/unit/controllers/ctr-playlist-item-modal.tests.js, test/unit/controllers/ctr-presentation-list.tests.js
Fixing styles for sort filters
Setting default sort by Name for Presentations
Storage-selector returns array of files; picking first one
[stage-2]
=> Presentation selector clickable-row

js/services/svc-playlist-factory.js, partials/playlist.html, test/e2e/pages/playlistPage.js, test/e2e/playlist.scenarios.js, test/unit/services/svc-playlist-factory.tests.js
http://screencast.com/t/ue0Rit5zdqaI
=> Implementing copy function [stage-2]

js/config/dev.js, js/config/prod.js, js/config/test.js, js/directives/dtv-schedule-fields.js, js/services/svc-playlist-factory.js, js/services/svc-schedule-factory.js, partials/schedule-fields.html, test/e2e/pages/scheduleAddPage.js, test/e2e/scheduleadd.scenarios.js, test/unit/services/svc-schedule-factory.tests.js
Button only shows if the schedule has been saved
=> Implemented schedule preview [stage-1]

js/config/dev.js, js/config/prod.js, js/config/test.js, test/unit/services/svc-schedule-factory.tests.js
Viewer doesn't work with https very well. Forgot that, switching to http.
@rodrigopavezi please review. Thanks.
=> User http for viewer url for preview [stage-2]

partials/schedule-add.html, partials/schedule-details.html
=> Disable html5 form validation [stage-1]

index.html, js/directives/dtv-presentation-name.js, js/services/svc-presentation-factory.js, js/services/svc-schedule-factory.js, partials/playlist-item.html, partials/playlist.html, partials/schedule-add.html, partials/schedule-details.html, test/e2e/add-presentation.scenarios.js, test/e2e/pages/playlistItemModalPage.js, test/e2e/pages/playlistPage.js, test/unit/services/svc-presentation-factory.tests.js, test/unit/services/svc-schedule-factory.tests.js
Directive displays presentation name based on id
Factory which caches presentations that were retrieved via API
TODO: Link list API to factory
Changed submitError variable to apiError in factories
=> Presentation name directive [stage-2]

js/services/svc-schedule.js, partials/playlist.html
Using track by field to prevent $$hashkey from being added
=> Add content field to save [stage-1]

bower.json, js/app.js
=> Updating CH to v1.4.2

partials/presentation-list.html, partials/schedules-list.html
Removed extra `div` which was preventing the scrolling directive from triggering.
[stage-2]
=> Fixing scrolling-list directive

js/services/svc-schedule-factory.js, js/services/svc-schedule.js, partials/schedule-add.html, partials/schedule-details.html, test/unit/services/svc-schedule-factory.tests.js
Saving distribution and distributeToAll fields
Initialize distribution as Array
Fixed API error retrieval functionality (_showErrorMessage)
Specify failed function name
Clearing error messages, loaders, etc before every API call
=> Fixed save error and updated error messages

index.html, js/app.js, partials/schedule-fields.html, test/e2e/add-distribution.scenarios.js, test/e2e/add-presentation.scenarios.js, test/e2e/add-url.scenarios.js, test/e2e/homepage.scenarios.js, test/e2e/pages/distributionModalPage.js, test/e2e/pages/presentationModalPage.js, test/e2e/pages/scheduleAddPage.js, test/e2e/playlist.scenarios.js, test/e2e/scheduleadd.scenarios.js, test/e2e/schedulelist.scenarios.js, test/e2e/signin.scenarios.js, test/unit/controllers/ctr-schedule-add.tests.js, test/unit/services/svc-schedule-factory.tests.js
=> Implemented distribution component

js/app.js, partials/landing-page.html, test/e2e/homepage.scenarios.js, test/e2e/pages/homepage.js
https://schedules-stage-0.risevision.com
=> Added landing page

partials/landing-page.html, test/e2e/homepage.scenarios.js, test/e2e/pages/homepage.js
https://schedules-stage-0.risevision.com/#/
=> Changed as per metadata doc

index.html
@alex-deaconu please review.
https://schedules-stage-0.risevision.com/#/
cheers
=> Updated metadata

index.html
=> Fixed twitter metadata

bower.json, index.html, js/app.js, js/services/svc-schedule.js, partials/playlist-item.html, partials/schedule-fields.html, test/e2e/add-timeline.scenarios.js, test/e2e/pages/scheduleAddPage.js, test/e2e/pages/timelineModalPage.js
Added field to playlist item and schedule fields
Saving timeline via API
Integrated directive
[stage-2]
=> Timeline directive integration

bower.json
=> Removing branch tag name

js/controllers/ctr-presentation-list.js, js/controllers/ctr-schedules-list.js, js/filters/ftr-presentation-status.js, partials/landing-page.html, partials/playlist-item.html, partials/playlist.html, partials/presentation-list.html, partials/presentation-modal.html, partials/schedule-fields.html, test/unit/controllers/ctr-presentation-list.tests.js, test/unit/filters/ftr-presentation-status.tests.js
=> Changed texts to use commons-i18n

bower.json, partials/schedule-fields.html
New CH and common-style versions
[stage-2]
=> Use timezone locale for Schedule timeline

test/e2e/add-timeline.scenarios.js, test/e2e/pages/scheduleAddPage.js, test/e2e/pages/timelineModalPage.js
=> New timeline component UX

partials/schedule-add.html, partials/schedule-details.html, partials/schedule-fields.html, test/e2e/add-distribution.scenarios.js, test/e2e/pages/distributionModalPage.js, test/e2e/pages/scheduleAddPage.js, test/e2e/scheduleadd.scenarios.js
@alex-deaconu please review.
cheers
=> Changed distribution as per new design

bower.json
[stage-1]
@ghislaineguerin please review. cheers
=> Upgraded common-style to v1.3.3

circle.yml, js/config/stage.js, test/e2e/add-distribution.scenarios.js, test/e2e/add-presentation.scenarios.js, test/e2e/add-timeline.scenarios.js, test/e2e/add-url.scenarios.js, test/e2e/homepage.scenarios.js, test/e2e/playlist.scenarios.js, test/e2e/scheduleadd.scenarios.js, test/e2e/schedulelist.scenarios.js, test/e2e/signin.scenarios.js
Similar to the fixes we implemented in the Editor app. Also, fixed `isPresent` error.
@rodrigopavezi @ezequielc please review. Thanks.
=> Fixing e2e test scenarios

js/config/stage.js, js/services/svc-schedule-factory.js, test/e2e/add-distribution.scenarios.js, test/e2e/add-timeline.scenarios.js, test/e2e/pages/timelineModalPage.js, test/e2e/scheduleadd.scenarios.js, test/unit/services/svc-schedule-factory.tests.js
Default distributeToAll should be false
Fix config module name
=> Updated timeline ux & tests

partials/playlist.html
@ezequielc @alex-deaconu fix for schedules playlist items list
=> fix list [stage-1]

partials/schedule-add.html
=> Add form ID

bower.json
@ghislaineguerin Please review. Cheers.
@rodrigopavezi @alex-deaconu FYI
=> update dependencies [stage-1]

circle.yml, package.json
report to the cci test reports folder
@alex-deaconu @ezequielc please review. 
cheers
=> Changed cci script to output e2e test

bower.json, gulpfile.js, test/e2e/cases/add-distribution.js, test/unit/controllers/ctr-presentation-list.tests.js, test/unit/controllers/ctr-schedule-add.tests.js, test/unit/controllers/ctr-schedule-details.tests.js, test/unit/controllers/ctr-schedules-list.tests.js
@ezequielc please review. cheers
=> Upgraded CH and CS

README.md, gulpfile.js, package.json
@rodrigopavezi Please review. Thanks
=> Code coverage

package.json
@ezequielc please review. cheers
=> added version to the rv-common-e2e

bower.json, partials/playlist-item.html, partials/presentation-modal.html
@rodrigopavezi Please review. Cheers
=> Fix mobile forms

bower.json, js/config/test.js
@ezequielc @rodrigopavezi 
Please review:
Update to Common Style v1.3.21, due to a label color bug.
I also changed to single quotes in `test.js` as advised by the JS linter.
Thx!
=> Update to Common Style v.1.3.21 [stage-1]

bower.json, gulpfile.js, index.html, package.json, test/e2e/cases/homepage.js, test/e2e/pages/homepage.js
@ezequielc please review. cheers
=> Upgraded to CH with auth 2

bower.json, package.json
@rodrigopavezi Please review. Cheers
=> Revert CH version

bower.json, partials/schedule-add.html, partials/schedule-details.html, partials/schedules-list.html
Use require-role directive to remove actions if not allowed
=> Check Content Publisher role

gulpfile.js, index.html, js/app.js, package.json
=> Prepopulate partials into templateCache

circle.yml, js/controllers/ctr-schedule-add.js, js/controllers/ctr-schedule-details.js, js/controllers/ctr-schedules-list.js, js/directives/dtv-schedule-fields.js, partials/schedule-fields.html, partials/schedules-list.html, test/e2e/cases/add-distribution.js, test/e2e/pages/playlistItemModalPage.js, test/unit/controllers/ctr-schedule-add.tests.js, test/unit/controllers/ctr-schedule-details.tests.js, test/unit/controllers/ctr-schedules-list.tests.js
- Tracking schedules events
- Fix E2E tests
@alex-deaconu Please review. Thanks
=> Track schedule events
